#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Groovy Shared Library

on:
  push:
    branches:
      - master
      - main
    paths:
      - src/**/*.groovy
      - vars/*.groovy
  pull_request:
    branches:
      - master
      - main
    paths:
      - src/**/*.groovy
      - vars/*.groovy
  workflow_dispatch:

permissions:
  contents: read

jobs:
  groovyc:
    if: github.event.repository.fork == false
    name: Groovy Shared Library
    uses: HariSekhon/GitHub-Actions/.github/workflows/groovyc.yaml@master
